#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)
protected_brunches='master|main'
if [[ $current_branch =~ $protected_brunches ]]; then
  echo "You can't push to $current_branch branch"
  exit 1
fi

exit 0
